-- SQL query to insert parsed products into svt_web_products
INSERT INTO `svt_web_products` (`name`, `slug`, `category_id`, `category_slug`, `price_label`, `availability`, `image_url`) VALUES
('iSteel TMT Bars', 'isteel-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('ARS TMT Bars', 'ars-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Arun Plus TMT Bars', 'arun-plus-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('GBR TMT Bars', 'gbr-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Pulkit TMT Bars', 'pulkit-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('JSW TMT Bars', 'jsw-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Amman Try TMT Bars', 'amman-try-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Blue Gold TMT Bars', 'blue-gold-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Suryadev TMT Bars', 'suryadev-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Vicky TMT Bars', 'vicky-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Suntech TMT Bars', 'suntech-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Thirumala TMT Bars', 'thirumala-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Thala TMT Bars', 'thala-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Jindal Panther TMT Bars', 'jindal-panther-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Sail TMT Bars', 'sail-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Vizag TMT Bars', 'vizag-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Tata Tiscon TMT Bars', 'tata-tiscon-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Brite TMT Bars', 'brite-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('MCR TMT Bars', 'mcr-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Agni TMT Bars', 'agni-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Ashok TMT Bars', 'ashok-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Aditya TMT Bars', 'aditya-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Pon Surya TMT Bars', 'pon-surya-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Kamachi TMT Bars', 'kamachi-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Tulsyan TMT Bars', 'tulsyan-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('6mm TMT Bars', '6mm-tmt-bars', 1, 'tmt', 'Call for Price', 'in_stock', NULL),
('Size: 3x3', 'size-3x3', 2, 'rings', 'Call for Price', 'in_stock', NULL),
('Size: 4x4', 'size-4x4', 2, 'rings', 'Call for Price', 'in_stock', NULL),
('Size: 7x3', 'size-7x3', 2, 'rings', 'Call for Price', 'in_stock', NULL),
('Size: 7x4', 'size-7x4', 2, 'rings', 'Call for Price', 'in_stock', NULL),
('Size: 7x7', 'size-7x7', 2, 'rings', 'Call for Price', 'in_stock', NULL),
('Size: 10x3', 'size-10x3', 2, 'rings', 'Call for Price', 'in_stock', NULL),
('Size: 10x4', 'size-10x4', 2, 'rings', 'Call for Price', 'in_stock', NULL),
('Size: 10x7', 'size-10x7', 2, 'rings', 'Call for Price', 'in_stock', NULL),
('Size: 12x7', 'size-12x7', 2, 'rings', 'Call for Price', 'in_stock', NULL),
('Size: 13x7', 'size-13x7', 2, 'rings', 'Call for Price', 'in_stock', NULL),
('Tata Bluescope', 'tata-bluescope', 3, 'rsheets', 'Call for Price', 'in_stock', NULL),
('JSW Pragati Plus', 'jsw-pragati-plus', 3, 'rsheets', 'Call for Price', 'in_stock', NULL),
('JSW Coloron Plus', 'jsw-coloron-plus', 3, 'rsheets', 'Call for Price', 'in_stock', NULL),
('Asian', 'asian', 3, 'rsheets', 'Call for Price', 'in_stock', NULL),
('Colourshine', 'colourshine', 3, 'rsheets', 'Call for Price', 'in_stock', NULL),
('AMNS', 'amns', 3, 'rsheets', 'Call for Price', 'in_stock', NULL),
('MS Pipe', 'ms-pipe', 4, 'pipes', 'Call for Price', 'in_stock', NULL),
('GI Pipe', 'gi-pipe', 4, 'pipes', 'Call for Price', 'in_stock', NULL),
('GP Pipe', 'gp-pipe', 4, 'pipes', 'Call for Price', 'in_stock', NULL),
('JSW MS Sheet', 'jsw-ms-sheet', 5, 'sheets', 'Call for Price', 'in_stock', NULL),
('Tata MS Sheet', 'tata-ms-sheet', 5, 'sheets', 'Call for Price', 'in_stock', NULL),
('Sail MS Sheet', 'sail-ms-sheet', 5, 'sheets', 'Call for Price', 'in_stock', NULL),
('Vizag MS Sheet', 'vizag-ms-sheet', 5, 'sheets', 'Call for Price', 'in_stock', NULL),
('JSW GI Sheet', 'jsw-gi-sheet', 5, 'sheets', 'Call for Price', 'in_stock', NULL),
('Tata GI Sheet', 'tata-gi-sheet', 5, 'sheets', 'Call for Price', 'in_stock', NULL),
('Ultratech Cement', 'ultratech-cement', 6, 'cement', 'Call for Price', 'in_stock', NULL),
('Coramendel Cement', 'coramendel-cement', 6, 'cement', 'Call for Price', 'in_stock', NULL),
('Ramco Cement', 'ramco-cement', 6, 'cement', 'Call for Price', 'in_stock', NULL),
('Maha HD Cement', 'maha-hd-cement', 6, 'cement', 'Call for Price', 'in_stock', NULL),
('Dalmia Cement', 'dalmia-cement', 6, 'cement', 'Call for Price', 'in_stock', NULL),
('Priya Cement', 'priya-cement', 6, 'cement', 'Call for Price', 'in_stock', NULL),
('Zuari Cement', 'zuari-cement', 6, 'cement', 'Call for Price', 'in_stock', NULL),
('Chetinadu Cement', 'chetinadu-cement', 6, 'cement', 'Call for Price', 'in_stock', NULL),
('JSW Cement', 'jsw-cement', 6, 'cement', 'Call for Price', 'in_stock', NULL),
('Ambuja Cement', 'ambuja-cement', 6, 'cement', 'Call for Price', 'in_stock', NULL),
('Ramco Sheets', 'ramco-sheets', 7, 'asbseet', 'Call for Price', 'in_stock', NULL),
('Charminar Sheets', 'charminar-sheets', 7, 'asbseet', 'Call for Price', 'in_stock', NULL),
('Visaka Sheets', 'visaka-sheets', 7, 'asbseet', 'Call for Price', 'in_stock', NULL),
('Roofit Sheets', 'roofit-sheets', 7, 'asbseet', 'Call for Price', 'in_stock', NULL),
('Angle Metals', 'angle-metals', 8, 'strmatr', 'Call for Price', 'in_stock', NULL),
('C Channel', 'c-channel', 8, 'strmatr', 'Call for Price', 'in_stock', NULL),
('I-Beam', 'i-beam', 8, 'strmatr', 'Call for Price', 'in_stock', NULL),
('Square Rod', 'square-rod', 8, 'strmatr', 'Call for Price', 'in_stock', NULL),
('Round Rod', 'round-rod', 8, 'strmatr', 'Call for Price', 'in_stock', NULL),
('Flat Rod', 'flat-rod', 8, 'strmatr', 'Call for Price', 'in_stock', NULL),
('Round - 7 inch', 'round-7-inch', 9, 'others', 'Call for Price', 'in_stock', NULL),
('Round', 'round', 9, 'others', 'Call for Price', 'in_stock', NULL),
('Cement Cover Block', 'cement-cover-block', 9, 'others', 'Call for Price', 'in_stock', NULL),
('Metal Screws', 'metal-screws', 9, 'others', 'Call for Price', 'in_stock', NULL),
('Base Plate', 'base-plate', 9, 'others', 'Call for Price', 'in_stock', NULL),
('Chicken Mesh', 'chicken-mesh', 9, 'others', 'Call for Price', 'in_stock', NULL),
('Welding Rod', 'welding-rod', 9, 'others', 'Call for Price', 'in_stock', NULL),
('Cutting Wheel', 'cutting-wheel', 9, 'others', 'Call for Price', 'in_stock', NULL),
('Nail', 'nail', 9, 'others', 'Call for Price', 'in_stock', NULL),
('J Hook', 'j-hook', 9, 'others', 'Call for Price', 'in_stock', NULL),
('Doctor Fix', 'doctor-fix', 9, 'others', 'Call for Price', 'in_stock', NULL),
('Ramco Super Shield', 'ramco-super-shield', 9, 'others', 'Call for Price', 'in_stock', NULL);